### ISSUE TITLE
Source Locations

### ISSUE THREAD

**Issue by aslushnikov** [shapesecurity/shift-parser-js#175]
Is there a way to retrieve source locations in terms of positions in source code?
I'm also interested in getting tokens.

Regards,
Andrey

**Comment by michaelficarra** [comment]
There is, but it is not yet documented. Pass `{loc: true}` as the second parameter to one of the parsing functions: https://github.com/shapesecurity/shift-parser-js/blob/ac01b130972502d4038633dd39aa2e8b21c5fc0c/src/index.js#L40

We don't plan to expose a token stream because it will impose some quite restrictive limitations on our implementation architecture. This may change in the future as things stabilise.
