### ISSUE TITLE
Keywords should not be represented by unicode escape sequences

### ISSUE THREAD

**Issue by dashed** [shapesecurity/shift-parser-js#307]
The following should throw an error:

``` js
// var foo = 42
\u0076\u0061\u{0072} foo = 42;
```

see: http://www.ecma-international.org/ecma-262/7.0/#sec-reserved-words

**Comment by bakkot** [comment]
Ah, that's kind of nasty. As far as I can tell, `i\u0066` ('if') is:
- prohibited in `i\u0066 (false) {}`
- prohibited in `var i\u0066;`
- legal in `({i\u0066: 0})`.

Even worse, `le\u0074` ('let') is:
- prohibited in `le\u0074 a;`
- legal in `var le\u0074;` outside of strict mode
- prohibited in `var le\u0074;` inside of strict mode
- legal in `({le\u0074: 0})` regardless.

The other relevant bit of the spec is https://tc39.github.io/ecma262/#sec-identifiers-static-semantics-early-errors: `It is a Syntax Error if StringValue of IdentifierName is the same String value as the StringValue of any ReservedWord except for yield.`

**Comment by michaelficarra** [comment]
We already have a disabled test for this early error: https://github.com/shapesecurity/shift-parser-js/blob/8dd9c785cf/test/early-errors.js#L193

Though we could stand to add more of @bakkot's examples. Once we fix this, we should remember to upstream the tests to test262-parser-tests.

**Comment by Shilpi3** [comment]
Following scripts are excluded from the tests due to similar test failures
Input [Script 594](https://github.com/tc39/test262-parser-tests/blob/master/early/594.script.js)
Input [Script 596](https://github.com/tc39/test262-parser-tests/blob/master/early/596.script.js)
Input [Script 597](https://github.com/tc39/test262-parser-tests/blob/master/early/597.script.js)
Input [Script 598](https://github.com/tc39/test262-parser-tests/blob/master/early/598.script.js)
